import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

import type { ExportArtifact, JobReadyPackage } from '@/src/features/resume/jobReady.types';
import { textFromUnknown } from '@/src/lib/renderText';

const EXPORT_DIR = `${FileSystem.cacheDirectory ?? ''}jobnova-exports/`;

type JobReadyPackageWithExtras = JobReadyPackage & {
  interviewStoryBank?: unknown;
  applicationAnswers?: unknown;
};

type ResolvedArtifact = Partial<ExportArtifact> & {
  fileName: string;
  label?: string;
  downloadUrl?: string;
};

function sanitizeFileName(value: string, fallback = 'JobNova_Export.txt'): string {
  const safe = String(value || '')
    .replace(/[\\/:*?"<>|]+/g, '_')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .trim();

  return safe || fallback;
}

function ensureExtension(fileName: string, fallbackExt = '.txt'): string {
  return /\.[a-z0-9]+$/i.test(fileName) ? fileName : `${fileName}${fallbackExt}`;
}

function mimeTypeForFileName(fileName: string): string | undefined {
  const lower = fileName.toLowerCase();

  if (lower.endsWith('.pdf')) return 'application/pdf';
  if (lower.endsWith('.docx')) {
    return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  }
  if (lower.endsWith('.doc')) return 'application/msword';
  if (lower.endsWith('.zip')) return 'application/zip';
  if (lower.endsWith('.txt')) return 'text/plain';
  if (lower.endsWith('.html')) return 'text/html';

  return undefined;
}

async function ensureExportDir(): Promise<string> {
  if (!EXPORT_DIR) {
    throw new Error('Could not access local device storage.');
  }

  const info = await FileSystem.getInfoAsync(EXPORT_DIR);

  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(EXPORT_DIR, { intermediates: true });
  }

  return EXPORT_DIR;
}

async function shareFile(uri: string, fileName: string) {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: mimeTypeForFileName(fileName) || 'text/plain',
      dialogTitle: `Save ${fileName}`,
    });
  }
}

function normalizeText(value: unknown): string {
  return textFromUnknown(value).trim();
}

function buildHtmlDocument(title: string, body: string): string {
  const escapedTitle = title
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const escapedBody = body
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\r?\n/g, '<br />');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapedTitle}</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; margin: 36px; color: #0f172a; }
      h1 { font-size: 24px; margin-bottom: 16px; }
      .note { margin-top: 24px; font-size: 12px; color: #475569; }
      .doc { white-space: normal; line-height: 1.6; font-size: 14px; }
    </style>
  </head>
  <body>
    <h1>${escapedTitle}</h1>
    <div class="doc">${escapedBody}</div>
    <div class="note">Generated by JobNova. When a live backend export is unavailable, this fallback file stays readable, printable, and easy to store on device.</div>
  </body>
</html>`;
}

function getExportArtifacts(data: JobReadyPackage): ExportArtifact[] {
  return Array.isArray(data.exportArtifacts) ? data.exportArtifacts : [];
}

function findArtifactByNameOrLabel(
  data: JobReadyPackage,
  target: string
): ExportArtifact | undefined {
  const needle = target.trim().toLowerCase();

  return getExportArtifacts(data).find((artifact) => {
    const fileName = String(artifact.fileName || '').trim().toLowerCase();
    const label = String(artifact.label || '').trim().toLowerCase();

    return fileName === needle || label === needle;
  });
}

function buildFullPackageText(data: JobReadyPackage): string {
  const enriched = data as JobReadyPackageWithExtras;
  const artifacts = getExportArtifacts(data);

  return [
    'JOBNOVA FULL PACKAGE',
    '====================',
    '',
    'ROLE',
    data.roleTitle || 'Target role',
    '',
    'COMPANY',
    data.companyName || 'Target company',
    '',
    'SUMMARY',
    data.exportSummary || 'Tailored package generated.',
    '',
    'TAILORED RESUME',
    normalizeText(data.tailoredResume || data.amendedResume) || 'Not available.',
    '',
    'COVER LETTER',
    normalizeText(data.coverLetter) || 'Not available.',
    '',
    'RECRUITER EMAIL SUBJECT',
    normalizeText(data.recruiterEmailSubject) || 'Not available.',
    '',
    'RECRUITER EMAIL BODY',
    normalizeText(data.recruiterEmailBody) || 'Not available.',
    '',
    'LINKEDIN HEADLINE',
    normalizeText(data.linkedinHeadline) || 'Not available.',
    '',
    'INTERVIEW STORY BANK',
    normalizeText(enriched.interviewStoryBank) || 'Not available.',
    '',
    'APPLICATION ANSWERS',
    normalizeText(enriched.applicationAnswers) || 'Not available.',
    '',
    'EXPORT FILES',
    ...(artifacts.length
      ? artifacts.map((artifact) =>
          `${artifact.label || artifact.fileName || 'Export'}${
            artifact.downloadUrl ? ` — ${artifact.downloadUrl}` : ''
          }`
        )
      : ['No generated export files yet.']),
  ].join('\n');
}

function resolveArtifact(
  artifactOrFileName: ExportArtifact | string,
  data?: JobReadyPackage
): ResolvedArtifact {
  if (typeof artifactOrFileName !== 'string') {
    return {
      ...artifactOrFileName,
      fileName: artifactOrFileName.fileName || artifactOrFileName.label || 'JobNova_Export',
    };
  }

  const target = artifactOrFileName.trim();
  const found = data ? findArtifactByNameOrLabel(data, target) : undefined;

  if (found) {
    return {
      ...found,
      fileName: found.fileName || found.label || target || 'JobNova_Export',
    };
  }

  return {
    fileName: target || 'JobNova_Export',
    label: target || 'JobNova Export',
    downloadUrl: '',
  };
}

export async function saveTextToDevice(fileName: string, content: string): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = ensureExtension(sanitizeFileName(fileName), '.txt');
  const uri = `${dir}${safeName}`;

  await FileSystem.writeAsStringAsync(uri, content || '', {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await shareFile(uri, safeName);
  return uri;
}

export async function saveHtmlToDevice(fileName: string, content: string): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = ensureExtension(sanitizeFileName(fileName), '.html');
  const uri = `${dir}${safeName}`;

  await FileSystem.writeAsStringAsync(uri, content || '', {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await shareFile(uri, safeName);
  return uri;
}

export async function saveSectionPreviewToDevice(
  sectionTitle: string,
  fileName: string,
  content: unknown
): Promise<string> {
  const text = typeof content === 'string' ? content : textFromUnknown(content);
  const body = [sectionTitle.toUpperCase(), '', text].join('\n');
  return saveTextToDevice(fileName, body);
}

export async function downloadRemoteFileToDevice(
  downloadUrl: string,
  fileName: string
): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = sanitizeFileName(fileName);
  const uri = `${dir}${safeName}`;

  const result = await FileSystem.downloadAsync(downloadUrl, uri);
  await shareFile(result.uri, safeName);

  return result.uri;
}

export function buildPackageSummaryText(data: JobReadyPackage): string {
  const enriched = data as JobReadyPackageWithExtras;
  const artifacts = getExportArtifacts(data);

  return [
    'JOBNOVA TAILORED PACKAGE',
    '',
    'ROLE',
    data.roleTitle || 'Target role',
    '',
    'COMPANY',
    data.companyName || 'Target company',
    '',
    'SUMMARY',
    data.exportSummary || 'Tailored package generated.',
    '',
    'TAILORED RESUME',
    normalizeText(data.tailoredResume || data.amendedResume),
    '',
    'COVER LETTER',
    normalizeText(data.coverLetter),
    '',
    'RECRUITER EMAIL SUBJECT',
    normalizeText(data.recruiterEmailSubject),
    '',
    'RECRUITER EMAIL BODY',
    normalizeText(data.recruiterEmailBody),
    '',
    'LINKEDIN HEADLINE',
    normalizeText(data.linkedinHeadline),
    '',
    'INTERVIEW STORY BANK',
    normalizeText(enriched.interviewStoryBank),
    '',
    'APPLICATION ANSWERS',
    normalizeText(enriched.applicationAnswers),
    '',
    'EXPORT FILES',
    ...(artifacts.length
      ? artifacts.map((artifact) =>
          `${artifact.label || artifact.fileName || 'Export'}${
            artifact.downloadUrl ? ` — ${artifact.downloadUrl}` : ''
          }`
        )
      : ['No generated export files yet.']),
  ].join('\n');
}

export async function savePackageSummaryToDevice(data: JobReadyPackage): Promise<string> {
  const fileName = ensureExtension(
    sanitizeFileName(
      `${data.roleTitle || 'JobNova'}_${data.companyName || 'Package'}_Summary`,
      'JobNova_Package_Summary.txt'
    ),
    '.txt'
  );

  return saveTextToDevice(fileName, buildPackageSummaryText(data));
}

export async function savePackageEmailPreviewToDevice(data: JobReadyPackage): Promise<string> {
  const subject = normalizeText(data.recruiterEmailSubject) || 'Recruiter Email';
  const body = normalizeText(data.recruiterEmailBody);
  const html = buildHtmlDocument(subject, body);

  const fileName = ensureExtension(
    sanitizeFileName(
      `${data.roleTitle || 'JobNova'}_${data.companyName || 'Recruiter'}_Email`,
      'JobNova_Recruiter_Email.html'
    ),
    '.html'
  );

  return saveHtmlToDevice(fileName, html);
}

export async function saveFullPackageToDevice(data: JobReadyPackage): Promise<string> {
  const fileName = ensureExtension(
    sanitizeFileName(
      `${data.roleTitle || 'JobNova'}_${data.companyName || 'Package'}_Full_Package`,
      'JobNova_Full_Package.txt'
    ),
    '.txt'
  );

  return saveTextToDevice(fileName, buildFullPackageText(data));
}

export async function savePackageArtifactToDevice(
  artifactOrFileName: ExportArtifact | string,
  data?: JobReadyPackage
): Promise<string> {
  const artifact = resolveArtifact(artifactOrFileName, data);

  const fileName = ensureExtension(
    sanitizeFileName(
      artifact.fileName || artifact.label || 'JobNova_Export',
      'JobNova_Export.txt'
    ),
    '.txt'
  );

  if (artifact.downloadUrl) {
    return downloadRemoteFileToDevice(artifact.downloadUrl, fileName);
  }

  const fallbackContent = [
    artifact.label || artifact.fileName || 'Export',
    '',
    'This export file is not available for direct download yet.',
    'Generate the package again or connect the live backend export service.',
  ].join('\n');

  return saveTextToDevice(fileName, fallbackContent);
}

export async function saveNamedPackageArtifactToDevice(
  data: JobReadyPackage,
  artifactNameOrLabel: string
): Promise<string> {
  const artifact = findArtifactByNameOrLabel(data, artifactNameOrLabel);

  if (!artifact) {
    throw new Error(`Could not find export artifact "${artifactNameOrLabel}".`);
  }

  return savePackageArtifactToDevice(artifact, data);
}
