import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

import type { ExportArtifact, JobReadyPackage } from '@/src/features/resume/jobReady.types';
import { textFromUnknown } from '@/src/lib/renderText';

const EXPORT_DIR = `${FileSystem.documentDirectory ?? ''}jobnova-exports/`;

function sanitizeFileName(value: string, fallback = 'JobNova_Export.txt'): string {
  const safe = String(value || '')
    .replace(/[\\/:*?"<>|]+/g, '_')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .trim();
  return safe || fallback;
}

function ensureExtension(fileName: string, fallbackExt = '.txt'): string {
  return /\.[a-z0-9]+$/i.test(fileName) ? fileName : `${fileName}${fallbackExt}`;
}

function mimeTypeForFileName(fileName: string): string | undefined {
  const lower = fileName.toLowerCase();
  if (lower.endsWith('.pdf')) return 'application/pdf';
  if (lower.endsWith('.docx')) return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  if (lower.endsWith('.doc')) return 'application/msword';
  if (lower.endsWith('.zip')) return 'application/zip';
  if (lower.endsWith('.txt')) return 'text/plain';
  if (lower.endsWith('.html')) return 'text/html';
  return undefined;
}

async function ensureExportDir(): Promise<string> {
  if (!EXPORT_DIR) throw new Error('Could not access local device storage.');
  const info = await FileSystem.getInfoAsync(EXPORT_DIR);
  if (!info.exists) {
    await FileSystem.makeDirectoryAsync(EXPORT_DIR, { intermediates: true });
  }
  return EXPORT_DIR;
}

async function shareFile(uri: string, fileName: string) {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: mimeTypeForFileName(fileName) || 'text/plain',
      dialogTitle: `Save ${fileName}`
    });
  }
}

export async function saveTextToDevice(fileName: string, content: string): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = ensureExtension(sanitizeFileName(fileName), '.txt');
  const uri = `${dir}${safeName}`;
  await FileSystem.writeAsStringAsync(uri, content || '', { encoding: FileSystem.EncodingType.UTF8 });
  await shareFile(uri, safeName);
  return uri;
}

export async function saveHtmlToDevice(fileName: string, content: string): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = ensureExtension(sanitizeFileName(fileName), '.html');
  const uri = `${dir}${safeName}`;
  await FileSystem.writeAsStringAsync(uri, content || '', { encoding: FileSystem.EncodingType.UTF8 });
  await shareFile(uri, safeName);
  return uri;
}

function buildHtmlDocument(title: string, body: string): string {
  const escapedTitle = title.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const escapedBody = body
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br />');

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapedTitle}</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; margin: 36px; color: #0f172a; }
      h1 { font-size: 24px; margin-bottom: 16px; }
      .note { margin-top: 24px; font-size: 12px; color: #475569; }
      .doc { white-space: normal; line-height: 1.6; font-size: 14px; }
    </style>
  </head>
  <body>
    <h1>${escapedTitle}</h1>
    <div class="doc">${escapedBody}</div>
    <div class="note">Generated by JobNova. When a live backend export is unavailable, this fallback file stays readable, printable, and easy to store on device.</div>
  </body>
</html>`;
}

export async function saveSectionPreviewToDevice(sectionTitle: string, fileName: string, content: unknown): Promise<string> {
  const text = typeof content === 'string' ? content : textFromUnknown(content);
  const body = [sectionTitle.toUpperCase(), '', text].join('\n');
  return saveTextToDevice(fileName, body);
}

export async function downloadRemoteFileToDevice(downloadUrl: string, fileName: string): Promise<string> {
  const dir = await ensureExportDir();
  const safeName = sanitizeFileName(fileName);
  const uri = `${dir}${safeName}`;
  const result = await FileSystem.downloadAsync(downloadUrl, uri);
  await shareFile(result.uri, safeName);
  return result.uri;
}

export function buildPackageSummaryText(data: JobReadyPackage): string {
  return [
    'JOBNOVA TAILORED PACKAGE',
    '',
    'ROLE',
    data.roleTitle || 'Target role',
    '',
    'COMPANY',
    data.companyName || 'Target company',
    '',
    'SUMMARY',
    data.exportSummary || 'Tailored package generated.',
    '',
    'TAILORED RESUME',
    textFromUnknown(data.tailoredResume || data.amendedResume),
    '',
    'COVER LETTER',
    textFromUnknown(data.coverLetter),
    '',
    'RECRUITER EMAIL SUBJECT',
    textFromUnknown(data.recruiterEmailSubject),
    '',
    'RECRUITER EMAIL BODY',
    textFromUnknown(data.recruiterEmailBody),
    '',
    'LINKEDIN HEADLINE',
    textFromUnknown(data.linkedinHeadline),
    '',
    'LINKEDIN ABOUT',
    textFromUnknown(data.linkedinAbout),
    '',
    'EXPORT NOTE',
    'This device copy was generated by the mobile app. When a live backend export is unavailable, JobNova creates readable fallback documents instead of fake or broken files.'
  ]
    .filter(Boolean)
    .join('\n');
}

export function buildArtifactText(artifact: ExportArtifact, data: JobReadyPackage): string {
  switch (artifact.type) {
    case 'resume':
      return textFromUnknown(data.tailoredResume || data.amendedResume);
    case 'cover-letter':
      return textFromUnknown(data.coverLetter);
    case 'recruiter-email':
      return ['SUBJECT', textFromUnknown(data.recruiterEmailSubject), '', 'BODY', textFromUnknown(data.recruiterEmailBody)].join('\n');
    default:
      return buildPackageSummaryText(data);
  }
}

async function saveFallbackDocument(artifact: ExportArtifact, data: JobReadyPackage): Promise<string> {
  const text = buildArtifactText(artifact, data);
  const title = `${artifact.label} — ${data.roleTitle || 'JobNova Export'}`;

  if (artifact.format === 'docx') {
    const html = buildHtmlDocument(title, text);
    const docName = ensureExtension(sanitizeFileName(artifact.fileName.replace(/\.docx$/i, '.doc')), '.doc');
    return saveHtmlToDevice(docName, html);
  }

  if (artifact.format === 'pdf') {
    const html = buildHtmlDocument(title, text);
    const htmlName = ensureExtension(sanitizeFileName(artifact.fileName.replace(/\.pdf$/i, '.html')), '.html');
    return saveHtmlToDevice(htmlName, html);
  }

  return saveTextToDevice(artifact.fileName, text);
}

export async function savePackageArtifactToDevice(artifact: ExportArtifact, data: JobReadyPackage): Promise<string> {
  if (artifact.downloadUrl && !String(artifact.downloadUrl).includes('undefined')) {
    return downloadRemoteFileToDevice(artifact.downloadUrl, artifact.fileName);
  }
  return saveFallbackDocument(artifact, data);
}

export async function saveFullPackageToDevice(data: JobReadyPackage): Promise<string> {
  const role = sanitizeFileName(data.roleTitle || 'Tailored_Package', 'Tailored_Package');
  if (data.packageBundleUrl && !String(data.packageBundleUrl).includes('undefined')) {
    return downloadRemoteFileToDevice(
      data.packageBundleUrl,
      data.packageBundleFileName || `JobNova_${role}_Full_Package.zip`
    );
  }
  const html = buildHtmlDocument(`JobNova Full Package — ${data.roleTitle || 'Tailored Package'}`, buildPackageSummaryText(data));
  return saveHtmlToDevice(`JobNova_${role}_Full_Package.html`, html);
}
