const OpenAI = require('openai');
const fs = require('fs');
const path = require('path');
const DEFAULT_TEXT_TIMEOUT_MS = Number(process.env.OPENAI_TIMEOUT_MS || 28000);
const DEFAULT_TRANSCRIBE_TIMEOUT_MS = Number(process.env.OPENAI_TRANSCRIBE_TIMEOUT_MS || 20000);
const DEFAULT_TTS_TIMEOUT_MS = Number(process.env.OPENAI_TTS_TIMEOUT_MS || 20000);
let cachedClient = null;
function asPositiveNumber(value, fallback) { const parsed = Number(value); return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback; }
function withTimeout(promise, ms = DEFAULT_TEXT_TIMEOUT_MS, label = 'OpenAI request') { const timeoutMs = asPositiveNumber(ms, DEFAULT_TEXT_TIMEOUT_MS); if (!timeoutMs) return promise; return Promise.race([promise, new Promise((_, reject) => setTimeout(() => reject(new Error(`${label} timed out after ${timeoutMs}ms`)), timeoutMs))]); }
function getOpenAI() { const apiKey = String(process.env.OPENAI_API_KEY || '').trim(); if (!apiKey) return null; if (!cachedClient) cachedClient = new OpenAI({ apiKey }); return cachedClient; }
function extractResponseText(response) { if (!response) return null; if (typeof response.output_text === 'string' && response.output_text.trim()) return response.output_text.trim(); const outputs = Array.isArray(response.output) ? response.output : []; const parts = []; for (const item of outputs) { const content = Array.isArray(item?.content) ? item.content : []; for (const entry of content) { if (typeof entry?.text === 'string' && entry.text.trim()) parts.push(entry.text.trim()); } } const combined = parts.join('\n').trim(); return combined || null; }
function toOpenAIError(error, fallback = 'OpenAI request failed.') { const message = error instanceof Error ? error.message : typeof error === 'string' ? error : fallback; if (/timeout/i.test(message)) return new Error(message); if (/401|incorrect api key|invalid api key|authentication/i.test(message)) return new Error('OpenAI authentication failed. Check OPENAI_API_KEY.'); if (/429|rate limit|quota/i.test(message)) return new Error('OpenAI rate limit reached. Try again shortly.'); return new Error(message || fallback); }
async function askOpenAI(prompt, options = {}) { const client = getOpenAI(); if (!client) return null; const input = String(prompt || '').trim(); if (!input) return null; try { const response = await withTimeout(client.responses.create({ model: String(options.model || process.env.OPENAI_MODEL || 'gpt-4o-mini').trim(), input, max_output_tokens: asPositiveNumber(options.maxOutputTokens || process.env.OPENAI_MAX_OUTPUT_TOKENS, 1600), temperature: typeof options.temperature === 'number' ? options.temperature : undefined }), asPositiveNumber(options.timeoutMs, DEFAULT_TEXT_TIMEOUT_MS), 'OpenAI text response'); return extractResponseText(response); } catch (error) { throw toOpenAIError(error, 'OpenAI text response failed.'); } }
async function transcribeAudio(filePath, options = {}) { const client = getOpenAI(); if (!client || !filePath || !fs.existsSync(filePath)) return null; try { const result = await withTimeout(client.audio.transcriptions.create({ file: fs.createReadStream(filePath), model: String(options.model || process.env.OPENAI_TRANSCRIBE_MODEL || 'gpt-4o-mini-transcribe').trim() }), asPositiveNumber(options.timeoutMs, DEFAULT_TRANSCRIBE_TIMEOUT_MS), 'OpenAI transcription'); return typeof result?.text === 'string' ? result.text.trim() || null : null; } catch (error) { throw toOpenAIError(error, 'OpenAI transcription failed.'); } }
async function synthesizeSpeech(text, filePath, voice = 'alloy', options = {}) { const client = getOpenAI(); const input = String(text || '').trim(); if (!client || !input || !filePath) return null; try { const dir = path.dirname(filePath); if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true }); const speech = await withTimeout(client.audio.speech.create({ model: String(options.model || process.env.OPENAI_TTS_MODEL || 'gpt-4o-mini-tts').trim(), voice: String(voice || 'alloy').trim(), input: input.slice(0, 4000), format: 'mp3' }), asPositiveNumber(options.timeoutMs, DEFAULT_TTS_TIMEOUT_MS), 'OpenAI speech'); const buffer = Buffer.from(await speech.arrayBuffer()); fs.writeFileSync(filePath, buffer); return filePath; } catch (error) { throw toOpenAIError(error, 'OpenAI speech synthesis failed.'); } }
module.exports = { getOpenAI, askOpenAI, transcribeAudio, synthesizeSpeech };
