import { assertRuntimeEnv, env } from '@/src/lib/env';

type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
type RequestOptions = { method?: HttpMethod; body?: unknown; token?: string | null; headers?: Record<string, string | null | undefined>; timeoutMs?: number; };
type ApiErrorPayload = { message?: string; error?: string; requestId?: string; details?: unknown; };
export class ApiRequestError extends Error { status?: number; requestId?: string; details?: unknown; constructor(message: string, init?: { status?: number; requestId?: string; details?: unknown }) { super(message); this.name = 'ApiRequestError'; this.status = init?.status; this.requestId = init?.requestId; this.details = init?.details; } }
const joinUrl = (baseUrl: string, path: string) => `${baseUrl.replace(/\/+$/, '')}${path.startsWith('/') ? path : `/${path}`}`;
function ensureApiBaseUrl(): string { assertRuntimeEnv(); if (env.useMockApi) return env.apiBaseUrl || 'http://localhost:4000'; if (!env.apiBaseUrl) throw new Error('Live API mode is enabled but EXPO_PUBLIC_API_BASE_URL is missing.'); return env.apiBaseUrl; }
function sanitizeHeaders(headers?: Record<string, string | null | undefined>): Record<string, string> { return Object.entries(headers || {}).reduce<Record<string, string>>((acc, [key, value]) => { const safeKey = typeof key === 'string' ? key.trim() : ''; if (!safeKey || value == null) return acc; acc[safeKey] = String(value); return acc; }, {}); }
function sanitizeBody(value: unknown): unknown { if (Array.isArray(value)) return value.map(sanitizeBody); if (value && typeof value === 'object') return Object.entries(value as Record<string, unknown>).reduce<Record<string, unknown>>((acc, [key, entry]) => { if (!key || entry === undefined) return acc; acc[key] = sanitizeBody(entry); return acc; }, {}); return value; }
function buildNetworkError(error: unknown): Error { const message = error instanceof Error ? error.message : String(error ?? ''); if (/aborted|timed out/i.test(message)) return new Error('The request timed out. Check the backend URL, your network connection, or the server logs.'); if (/network request failed|failed to fetch|load failed/i.test(message)) return new Error('Could not reach the backend. Verify EXPO_PUBLIC_API_BASE_URL, confirm the server is running, and check network access from the device.'); return error instanceof Error ? error : new Error(message || 'Request failed.'); }
async function parseErrorResponse(response: Response): Promise<ApiRequestError> { const contentType = response.headers.get('content-type') ?? ''; const isJson = contentType.includes('application/json'); let payload: ApiErrorPayload | string | null = null; try { payload = isJson ? await response.json() : await response.text(); } catch { payload = null; } const message = typeof payload === 'string' ? payload || `Request failed with status ${response.status}` : payload?.message || payload?.error || `Request failed with status ${response.status}`; return new ApiRequestError(message, { status: response.status, requestId: typeof payload === 'object' ? payload?.requestId : undefined, details: typeof payload === 'object' ? payload?.details : undefined }); }
async function parseResponse<T>(response: Response): Promise<T> { const contentType = response.headers.get('content-type') ?? ''; const isJson = contentType.includes('application/json'); if (!response.ok) throw await parseErrorResponse(response); if (!isJson) return {} as T; return response.json() as Promise<T>; }
async function fetchWithTimeout(input: string, init: RequestInit, timeoutMs = 12000): Promise<Response> { const controller = new AbortController(); const timeoutId = setTimeout(() => controller.abort(), timeoutMs); try { return await fetch(input, { ...init, signal: controller.signal }); } catch (error) { throw buildNetworkError(error); } finally { clearTimeout(timeoutId); } }
export async function apiRequest<T>(path: string, options: RequestOptions = {}): Promise<T> { const baseUrl = ensureApiBaseUrl(); const headers = sanitizeHeaders({ 'Content-Type': 'application/json', ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}), ...(options.headers || {}) }); const body = options.body !== undefined ? JSON.stringify(sanitizeBody(options.body)) : undefined; const response = await fetchWithTimeout(joinUrl(baseUrl, path), { method: options.method ?? 'GET', headers, body }, options.timeoutMs); return parseResponse<T>(response); }
export async function apiFormRequest<T>(path: string, formData: FormData, token?: string | null, timeoutMs = 30000): Promise<T> { const baseUrl = ensureApiBaseUrl(); const headers = sanitizeHeaders(token ? { Authorization: `Bearer ${token}` } : undefined); const response = await fetchWithTimeout(joinUrl(baseUrl, path), { method: 'POST', headers, body: formData }, timeoutMs); return parseResponse<T>(response); }
const isUnauthorizedError = (error: unknown) => error instanceof ApiRequestError && error.status === 401 || /unauthorized|sign in again|401/i.test(error instanceof Error ? error.message : String(error ?? ''));
export async function optionalAuthApiRequest<T>(path: string, token: string | null | undefined, options: Omit<RequestOptions, 'token'> = {}): Promise<T> { try { return await apiRequest<T>(path, { ...options, token: token || null }); } catch (error) { if (token && isUnauthorizedError(error)) return apiRequest<T>(path, { ...options, token: null }); throw error; } }
export async function optionalAuthFormRequest<T>(path: string, formData: FormData, token?: string | null, timeoutMs = 30000): Promise<T> { try { return await apiFormRequest<T>(path, formData, token || null, timeoutMs); } catch (error) { if (token && isUnauthorizedError(error)) return apiFormRequest<T>(path, formData, null, timeoutMs); throw error; } }
