const { Queue, Worker } = require('bullmq');
const { randomUUID } = require('crypto');
const { getRedis, redisHealthcheck } = require('./redis');
const { log } = require('./telemetry');
const { processJob } = require('../services/jobProcessor');
const { queueWorkerEnabled } = require('../config/env');
const memoryJobs = []; let queue = null; let worker = null; let queueDisabledReason = '';
const touch = (job, patch = {}) => Object.assign(job, patch, { updatedAt: new Date().toISOString() });
const markRunning = (job) => touch(job, { status: 'processing', progress: Math.max(20, Number(job.progress || 0)) });
const markDone = (job, result) => touch(job, { status: 'completed', progress: 100, result, errorMessage: null });
const markFailed = (job, error) => touch(job, { status: 'failed', progress: 100, errorMessage: error?.message || 'Queue job failed.' });
function getQueueMode() { if (!queueWorkerEnabled) return 'disabled'; if (queueDisabledReason) return 'in-memory'; const connection = getRedis(); return connection ? 'bullmq' : 'in-memory'; }
function disableQueue(reason) { queueDisabledReason = reason || 'queue unavailable'; try { queue?.close?.().catch?.(() => undefined); } catch {} try { worker?.close?.().catch?.(() => undefined); } catch {} queue = null; worker = null; log('warn', 'queue_disabled', { reason: queueDisabledReason }); }
function getQueue() { if (!queueWorkerEnabled || queueDisabledReason) return null; const connection = getRedis(); if (!connection) return null; if (!queue) { try { queue = new Queue('jobnova-v75', { connection }); } catch (error) { disableQueue(error?.message || 'bullmq queue initialization failed'); return null; } } return queue; }
function startWorker(onEvent) { if (!queueWorkerEnabled || queueDisabledReason || worker) return worker; const connection = getRedis(); if (!connection) return null; try { worker = new Worker('jobnova-v75', async (job) => { const result = await processJob(job.name, job.data?.payload || {}); onEvent?.({ jobId: job.data?.appJobId || job.id, status: 'completed', progress: 100, result, queueJobId: job.id }); return result; }, { connection }); } catch (error) { disableQueue(error?.message || 'bullmq worker initialization failed'); return null; } worker.on('active', (job) => onEvent?.({ jobId: job.data?.appJobId || job.id, status: 'processing', progress: 20, queueJobId: job.id })); worker.on('failed', (job, error) => onEvent?.({ jobId: job?.data?.appJobId || job?.id, status: 'failed', progress: 100, errorMessage: error?.message || 'Queue job failed.', queueJobId: job?.id })); worker.on('error', (error) => { disableQueue(error?.message || 'bullmq worker error'); log('error', 'bullmq_worker_error', { message: error.message }); }); return worker; }
async function runInMemoryJob(job, kind, payload, onLocalUpdate) { try { markRunning(job); onLocalUpdate?.({ ...job }); const result = await processJob(kind, payload); markDone(job, result); onLocalUpdate?.({ ...job }); } catch (error) { markFailed(job, error); onLocalUpdate?.({ ...job }); } }
async function enqueue(kind, payload = {}, onLocalUpdate) { const job = { id: randomUUID(), kind, type: kind, status: 'queued', progress: 0, payload, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), result: null, errorMessage: null, queueMode: getQueueMode() }; memoryJobs.unshift(job); const queueInstance = getQueue(); if (queueInstance) { try { const queued = await queueInstance.add(kind, { appJobId: job.id, payload }, { attempts: 3, backoff: { type: 'exponential', delay: 1500 }, removeOnComplete: 100, removeOnFail: 100 }); job.queueJobId = queued.id; job.queueMode = 'bullmq'; return job; } catch (error) { disableQueue(error?.message || 'bullmq enqueue failed'); job.queueMode = 'in-memory'; } } setTimeout(() => { void runInMemoryJob(job, kind, payload, onLocalUpdate); }, 25); return job; }
const listJobs = (limit = 100) => memoryJobs.slice(0, limit);
async function queueHealthSummary() { const redis = await redisHealthcheck(); return { queueMode: getQueueMode(), workerEnabled: Boolean(queueWorkerEnabled), disabledReason: queueDisabledReason || '', redis, queueDepth: listJobs(500).filter((job) => job.status === 'queued' || job.status === 'processing').length }; }
module.exports = { enqueue, listJobs, startWorker, getQueue, getQueueMode, queueHealthSummary, markRunning, markDone, markFailed };
